add_newline = true

[character]
success_symbol = "[â†’](bold green)"
error_symbol = "[â†’](bold red)"
vicmd_symbol = "[â†](bold green)"

[username]
style_user = "bold cyan"
style_root = "bold red"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "at [$hostname](yellow) "
disabled = false

[directory]
format = "in [$path]($style) "
style = "bold green"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[git_branch]
symbol = "ðŸŒ± "

[conda]
ignore_base = false
format = "via [$environment](dimmed green) "
